spring:
    application:
        name: msclients

server:
    port: 0

eureka:
    client:
        service-url:
            defaultZone: http://ms-credit-card-user:eyJhbGciOiJSUzI1NiIsInR5cCIg@localhost:8761/eureka
    instance:
        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}