spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: ms-credit-card-user
      password: eyJhbGciOiJSUzI1NiIsInR5cCIg

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
