spring:
  application:
    name: mscreditappraiser
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://ms-credit-card-user:eyJhbGciOiJSUzI1NiIsInR5cCIg@localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    issuance-cards: issuance-cards

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: ./logs/log-file.log
